rotulator/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload_file, name='upload_file'),
    path('remove/', views.remove_file, name='remove_file'),
    path('download_file/', views.download_file, name='download_file'),
    path('change_disc_table/', views.change_disc_table, name='change_disc_table'),
    path('run/', views.run, name='run'),
    path('show_config/<str:alg>', views.show_config, name='show_config'),
]

rotulator/rotulator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

rotulator/core/models.py
from django.db import models

class Arquivo(models.Model):
	arquivo = models.FileField(upload_to="uploads/")
	arquivo_discretizado = models.FileField(upload_to="uploads/", null=True)
	arquivo_rotulo = models.FileField(upload_to="uploads", null=True)

rotulator/core/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files import File
from .models import Arquivo
from .algoritmos import man_dados
from .algoritmos import discretizacao
from .algoritmos import classificacao
from .algoritmos import rotulacao 
import csv
import pandas as pd

def home(request):
	return render(request, 'core/home.html')

@csrf_exempt
def upload_file(request):
	data = {}

	try:
		file = request.FILES['file']		
	except:
		erro = "Selecione um arquivo no formato .csv."
		data['html_content_erro'] = render_to_string('core/parciais/parcial_erro.html',
			{'erro': erro})
		return JsonResponse(data)

	file_name = str(file).split('.')
	formato = file_name.pop()
	file_name = file_name[0].title() + " Dataset"

	if formato != "csv":
		erro = "O Arquivo deve ser no formato .csv."
		data['html_content_erro'] = render_to_string('core/parciais/parcial_erro.html',
			{'erro': erro})
		return JsonResponse(data)

	file_ = Arquivo(arquivo=file)
	file_.save()

	#Lê a base de dados no formato csv
	bd = man_dados.read_csv(file_.arquivo.url)

	colunas_discretizacao = [] # Colunas para a tabela de discretização
	colunas_cluster = [] # Colunas para escolha do cluster (contém todas)

	colunas_discretizacao, colunas_cluster = man_dados.disc_cluster_att(bd)

	data['file_id'] = file_.id
	data['html_content_algorithm'] = render_to_string('core/parciais/parcial_algoritmo.html',
				{'colunas': [], 'colunas2': colunas_cluster})
	data['html_content_file_name'] = render_to_string('core/parciais/parcial_file_name.html', 
				{'file_name': file_name})
	return JsonResponse(data)

def remove_file(request):
	data = {}

	try:
		file_id = request.GET['file_id']
		arquivo = Arquivo.objects.get(pk=file_id)
		arquivo.delete()
	except:
		pass
	return JsonResponse(data)

def download_file(request):
	id = request.GET['file_id']
	file = Arquivo.objects.get(pk=id)
	file = man_dados.read_csv(file.arquivo_discretizado.url)

	response = HttpResponse(file, content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename=new_db.csv'
	return response

def change_disc_table(request):
	data = {}

	cluster = request.GET['cluster']

	file_id = request.GET['file_id']
	file = Arquivo.objects.get(pk=file_id)
	file_path = file.arquivo.url

	bd = man_dados.read_csv(file.arquivo.url)
	colunas, _ = man_dados.disc_cluster_att(bd)
	limites = man_dados.num_instancias(bd, cluster)

	cont = 0
	for ind, c in enumerate(colunas):
		if c == cluster:
			del colunas[ind]
			break

	data['html_content_tabela'] = render_to_string('core/parciais/parcial_tabela_discretizacao.html',
				{'colunas': zip(colunas, limites)})
	return JsonResponse(data)

def show_config(request, alg):
	data = {}

	if alg == "mlp":
		data['html_content_config'] = render_to_string('core/parciais/parcial_mlp_config.html')
	else:
		data['html_content_config'] = render_to_string('core/parciais/parcial_cart_config.html')
	
	return JsonResponse(data)

def run(request):
	erro = None
	data = {}

	# Salva o caminho do arquivo
	file_id = request.GET['file_id']
	file= Arquivo.objects.get(pk=file_id)
	file_path = file.arquivo.url

	# Salva o atributo cluster da base
	try:
		attr_cluster = request.GET['cluster']
	except:
		erro = "O Atributo Cluster deve ser selecionado."
		data['html_content_erro'] = render_to_string('core/parciais/parcial_erro.html',
				{'erro': erro})
		return JsonResponse(data)

	# Verificando se é necessário discretizar
	try:
		no_discretization = request.GET['discretization']
	except:
		no_discretization = None

	faixas = []

	# Verificando se a lista de discretização está vazia
	ind_cluster = 0


	#------------------------------ DEFINIÇÂO DOS PARÂMETROS ------------------------------------------
	# Caminho da base de dados
	base_original = man_dados.read_csv(file_path) 

	# Salva o nome dos atributtos 
	nomes = man_dados.named(base_original)

	# Atributo cluster
	attr_name = attr_cluster

	#limite das faixas 
	limite = man_dados.num_instancias(base_original, attr_name)

	if no_discretization == None:
		for ind, att in enumerate(nomes):
			if att == attr_cluster:
				continue
			try:
				faixas.append(request.GET[att])
			except:
				pass


		# Verifica se existem campos de discretização vazios
		if '' in faixas or '0' in faixas:
			erro = "As Faixas de Discretização devem ser preenchidas corretamente."
			data['html_content_erro'] = render_to_string('core/parciais/parcial_erro.html',
				{'erro': erro})
			return JsonResponse(data)

		faixas = [int(v) for v in faixas]

		for ind, valor in enumerate(faixas):
			if valor > limite[ind] or valor < 1:
				erro = "As Faixas de Discretização devem ser positivas e obdecer aos limites definidos."
				data['html_content_erro'] = render_to_string('core/parciais/parcial_erro.html',
						{'erro': erro})
				return JsonResponse(data)

	#Configurações da rede neural
	classificador = request.GET['algorithm']
	num_folds = 5
	porcentagem_treino = 60
	

	#Configurações do discretizador
	discretizador = 'EFD'

	#Configurações do rotulador
	V = 10

	# Processamento da base 
	frames_originais = man_dados.group_separator(base_original, attr_name)

	# Parâmetros extras da mlp
	conf_mlp_list = ["hidden_layer_sizes", "activation", "learning_rate", "learning_rate_init", "max_iter", "momentum"]
	conf_mlp = {"hidden_layer_sizes": 10, "max_iter": 200}

	if classificador == "MLP":
		try:
			for p in conf_mlp_list:
				v = request.GET[p]
				if p in ["hidden_layer_sizes", "max_iter", ]:
					v = int(v)
				elif p in ["learning_rate_init", "momentum"]:
					v = float(v)
				conf_mlp[p] = v
		except:
			pass

	#---------------------- ESCOLHER UMA DAS ROTINAS -------------------------------------------------------------------------------------------
	if no_discretization is None:
		#Rotina para discretização
		disc = discretizacao.discretizador(base_original, faixas, discretizador, attr_name)
		base_discretizada = disc.ddb
		infor = disc.infor
		frames_discretizados = man_dados.group_separator(base_discretizada, attr_name)
		resultado_classificacao = classificacao.classifica_bd(frames_discretizados, classificador, attr_name, porcentagem_treino, num_folds, **conf_mlp )
		rotulo = rotulacao.rotular(frames_originais, frames_discretizados, resultado_classificacao, V, infor)
		discretizada = True
	else:
		#Rotina sem discretização
		resultado_classificacao = classificacao.classifica_bd(frames_originais, classificador, attr_name, porcentagem_treino, num_folds, **conf_mlp )
		rotulo = rotulacao.rotular(frames_originais, None, resultado_classificacao, V, None)
		discretizada = False

	# Preparação da string do rótulo para a tabela do rótulo.
	lista = []
	for cluster in rotulo:
		cluster2 = []
		cluster = cluster.split('\n')
		cluster.pop() # remove o 'lixo' deixado pelo ultimo \n na linha

		for linha in cluster:
			cluster2.append(linha.split(','))
		lista.append(cluster2)

	data['html_content_rotulo'] = render_to_string('core/parciais/parcial_rotulo.html', 
				{'lista': lista, "discretizada": discretizada})
	return JsonResponse(data)
	

rotulator/core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
	Theory by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>LINA | Rotulador</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link rel="stylesheet" href="{% static 'core/css/main.css' %}"/>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	</head>
	<body class="subpage">
		{% block content %}
        {% endblock %}
        
        <!-- Footer -->
		<footer id="footer" style="text-align: center;">
			<div class="inner">
				<div class="copyright">
					<b>LINA | Laboratório de Inteligência Artificial</b> 
					</br>
					Universidae Federal do Piauí.
					</br>
					Teresina, Piauí, Brasil.
					</br>
					<a href="mailto:lina@ufpi.edu.br">lina@ufpi.edu.br</a>
					</br>
					&copy; 2018 LINA. Powered using <a href="https://templated.co">Templated</a> theme.
				</div>
			</div>
		</footer>
	</body>	
	<!-- Scripts -->
	<script src="{% static 'core/js/jquery.min.js' %}"></script>
	<script src="{% static 'core/js/main.js' %}"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>		
</html>

rotulator/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
<!-- Header -->
<header id="header">
	<div class="inner">
		<a href="" class="logo">LINA | Laboratório de Inteligência Artificial</a>
		<nav id="nav">
			<a href="">Início</a>
			<a href="">Sobre</a>
		</nav>
		<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
	</div>
</header>
<!-- Three -->
<section id="three" class="wrapper">
	<div class="inner">
		<header class="align-center">
			<div class="principal">
				<h2>Rotulador LINA</h2>
			</div>
			<div id="file_select" >
				<form id="form_file" method="POST" onsubmit="return false" enctype="multipart/form-data">
					{% csrf_token %}
					<input style="margin: auto;" type="file" name="file">
					<p></p>
					<footer>
						<a onclick="UploadFile()" class="button special">Upload</a>
					</footer>
				</form>
			</div>
			<div id="file_name"></div>
			<input type="hidden" id="file_id" value="0">
			<div id="erro"></div>
		</header>
		<div id="algorithm">
		</div>
		<div id="rotulo">
		</div>
	</div>
</section>
{% endblock %}

rotulator/core/templates/core/parciais/parcial_algoritmo.html
<form id="form_algorithm">
	<div class="flex flex-2">
		<article>
			<header style="text-align: center">
				<h3>Discretização</h3>
			</header>
			<div id="tabela_discretizacao">
			{% include 'core/parciais/parcial_tabela_discretizacao.html' %}
			</div>
			<div style="text-align: center">
				<b>Não Discretizar</b>
				<td><input type="checkbox" name="discretization" id="discretization" onclick="changeDiscretization()"></td>
			</div>
		</article>
		<article>
			<header style="text-align: center">
				<h3>Cluster</h3>
			</header>
			<table style="text-align: center">
				<thead>
				<tr>
					<th>Atributo Cluster</th>
				</tr>
				</thead>
				<tbody>
					<tr>
						<td>
						<select name="cluster" id="cluster_select" onchange="changeDiscretizationTable()">
							<option disabled selected value> Selecione uma opção </option>
							{% for coluna in colunas2 %}
  							<option value="{{coluna}}">{{coluna}}</option>
  							{% endfor %}
						</select>
						</td>
					</tr>
				</tbody>
			</table>
			<header style="text-align: center">
				<h3>Algoritmo</h3>
			</header>
			<table style="text-align: center">
				<thead>
				<tr>
					<th>Multilayer Perceptron</th>
					<th>Classification And Regression Trees</th>
				</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<input type="radio" id="mlp" name="algorithm" value="MLP" onclick="changeSettings()" checked>
         					<label for="mlp">MLP</label>
						</td>
						<td>
							<input type="radio" id="cart" name="algorithm" value="CART" onclick="changeSettings()">
  							<label for="cart">CART</label>
						</td>
					</tr>
					<tr>
						<td>
							<a id="mlp_set" href="#" onclick="showConfig(1)"><i class="material-icons" style="color:#331a51">settings</i></a>
						</td>
						<td>
							<a id="cart_set" href="#" onclick="showConfig(2)"><i class="material-icons" style="color:#331a51">settings</i></a>
						</td>
					</tr>
				</tbody>
			</table>
			<div id="config" hidden></div>
			<input type="hidden" name="file_id"  id="file_id_algorithm" value="0">
			<header style="text-align: center">
				<a onclick="run()" class="button special">Run</a>
				<p>
					<div id="myProgress">
  						<div id="myBar">10%</div>
					</div>
				</p>
			</header>
		</article>
	</div>
</form>
	

rotulator/core/templates/core/parciais/parcial_erro.html
<div>
    <strong style="color: red">Atenção!</strong> {{erro}} {{" "}}
    <a href="#" onclick="hideError()"><i style="font-size: 15px;color:darkred;" class="material-icons">backspace</i></a>
</div>

rotulator/core/templates/core/parciais/parcial_file_name.html
<header><a href="{% url 'core:home' %}" class="button special">Voltar</a></header>
<footer id="breakline">
			<div class="inner">
				<div class="copyright">
				</div>
			</div>
	</footer>
<header style="text-align: center">
	<i class="material-icons">insert_drive_file</i>
	<h3>{{ file_name }}</h3>
</header>

rotulator/core/templates/core/parciais/parcial_mlp_config.html
<table>
	<thead>
		<tr>
			<th>Parâmetro</th>
			<th>Valor</th>
		</tr>
	</thead>
	<tbody id="colunas">
		<tr>
			<td>hidden_layer_sizes</td>
			<td><input type="number" name="hidden_layer_sizes" min="0" value="10"></td>
		</tr>
		<tr>
			<td>activation</td>
			<td>
				<select name="activation">
					<option>identity</option>
					<option>logistic</option>
					<option>tanh</option>
					<option selected>relu</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>learning_rate</td>
			<td>
				<select name="learning_rate">
					<option selected>constant</option>
					<option>invscaling</option>
					<option>adaptive</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>learning_rate_init</td>
			<td><input type="number" name="learning_rate_init" min="0" step="0.001" value="0.001"></td>
		</tr>
		<tr>
			<td>max_iter</td>
			<td><input type="number" name="max_iter" min="0" value="200"></td>
		</tr>
		<tr>
			<td>momentum</td>
			<td><input type="number" name="momentum" min="0" step="0.1" max="1" value="0.9"></td>
		</tr>	
	</tbody>
</table>

rotulator/core/templates/core/parciais/parcial_rotulo.html
<article>
	<header style="text-align: center">
		<h3>Rótulo</h3>
	</header>
	<table>
		<thead>
			<tr>
				<th>Cluster</th>
				<th>#Elementos</th>
				<th>Atributo</th>
				<th>{% if discretizada %} Faixa {% else %} Valor {% endif %}</th>
				<th>Relevância</th>
				<th>Erros</th>
				<th>Taxa de Acerto</th>
			</tr>
		</thead>
		<tbody>
			{% for cluster in lista %}
				
				{% for linha in cluster %}
				<tr>
					{% if forloop.counter == 1%}
						<td>{{forloop.parentloop.counter}}</td>
					{% else %}
						<td></td>
					{% endif %}
					{% for coluna in linha %}
						{% if forloop.counter == 1 and forloop.parentloop.counter > 1%}
							<td></td>
						{% endif %}
						<td>{{coluna}}</td>
					{% endfor %}
				</tr>
				{% endfor %}
				
			{% endfor %}
		</tbody>
	</table>
	<header style="text-align: center">
		<a onclick="downloadCsvFile()" class="button special">Baixar Base Discretizada</a>
		<a onclick="#" class="button special">Baixar Rótulo</a>
	</header>
	
</article>

rotulator/core/templates/core/parciais/parcial_tabela_discretizacao.html
<table>
	<thead>
		<tr>
			<th>#</th>
			<th>Atributos</th>
			<th>Intervalos</th>
			<th>Limite</th>
		</tr>
	</thead>
	<tbody id="colunas">
		{% for coluna,limite in colunas %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ coluna }} </td>
			<td><input type="number" name="{{coluna}}" min="1" max="{{limite}}" value="1"></td>
			<td>{{ limite }} </td>
		</tr>
		{% empty %}
        <tr>
          <td colspan="3" style="text-align: center;">Selecione o Atributo Cluster</td>
        </tr>
		{% endfor %}
	</tbody>
</table>